services:
    app:
        container_name: api
        env_file: .env
        build:
            context: .
            target: dev
            dockerfile: Dockerfile
        ports:
            - '3000:${PORT}'
        expose:
            - '3000'
        tty: true
        volumes:
            - ./:/app
        links:
            - database
        depends_on:
            database:
                condition: service_healthy
        networks:
            - tinker_network
        restart: always

    database:
        image: 'postgres:17.5-bookworm'
        container_name: db
        env_file: '.env'
        environment:
            POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
        ports:
            - 5432:5432
        # expose:
        #     - '5432'
        volumes:
            - 'db_data:/var/lib/postgresql/data'
        restart: on-failure
        healthcheck:
            test:
                [
                    'CMD',
                    'pg_isready',
                    '-q',
                    '-d',
                    '${DB_NAME}',
                    '-U',
                    '${DB_USER}',
                ]
            interval: 5s
            timeout: 3s
            retries: 3
        networks:
            - tinker_network

    queue:
        image: 'ghcr.io/riverqueue/riverui:master'
        container_name: queue
        env_file: '.env'
        environment:
            DATABASE_URL: ${DB_RIVER_URL}
            RIVER_BASIC_AUTH_USER: ${RIVER_UI_USER}
            RIVER_BASIC_AUTH_PASS: ${RIVER_UI_PASS}
        ports:
            - 8000:3000
        restart: on-failure
        networks:
            - tinker_network

    # postgres migration tool
    goose:
        container_name: goose-runner
        profiles: ['tools']
        env_file: .env
        build:
            context: .
            target: goose
            dockerfile: Dockerfile
        environment:
            GOOSE_DRIVER: postgres
            # GOOSE_DBSTRING: postgres://${DB_USER}:${DB_ROOT_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
            GOOSE_DBSTRING: $DB_ROOT_URL
            GOOSE_MIGRATION_DIR: /migrations
            NO_COLOR: false
        volumes:
            - ./internal/db/migrations:/migrations
        # https://github.com/pressly/goose?tab=readme-ov-file#usage
        entrypoint: ['goose', '-s', '-timeout', '5m']
        networks:
            - tinker_network
        depends_on:
            database:
                condition: service_healthy
        restart: never

    # river migration tool
    river:
        container_name: river-runner
        profiles: ['tools']
        env_file: .env
        build:
            context: .
            target: river
            dockerfile: Dockerfile
        entrypoint:
            ['river', '--line', 'main', '--database-url', '$DB_RIVER_URL']
        networks:
            - tinker_network
        depends_on:
            database:
                condition: service_healthy
        restart: never

volumes:
    db_data:

networks:
    tinker_network:
