// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCacheEntries = `-- name: DeleteCacheEntries :exec
DELETE FROM cache
WHERE
    key = ANY ($1::TEXT[])
`

func (q *Queries) DeleteCacheEntries(ctx context.Context, keys []string) error {
	_, err := q.db.Exec(ctx, deleteCacheEntries, keys)
	return err
}

const deleteCacheEntriesByPattern = `-- name: DeleteCacheEntriesByPattern :exec
DELETE FROM cache
WHERE
    key LIKE $1
`

// DeleteCacheEntriesByPattern takes a SQL LIKE pattern; callers translate the
// glob-style '*' they use elsewhere into '%'.
func (q *Queries) DeleteCacheEntriesByPattern(ctx context.Context, pattern string) error {
	_, err := q.db.Exec(ctx, deleteCacheEntriesByPattern, pattern)
	return err
}

const getCacheEntry = `-- name: GetCacheEntry :one
SELECT
    value
FROM
    cache
WHERE
    key = $1
    AND (
        expires_at IS NULL
        OR expires_at > NOW()
    )
`

// Queries for the shared UNLOGGED `cache` table. Every one of them treats an
// expired row as absent rather than deleting it inline; reaping is the purge
// job's business.
// GetCacheEntry reads a live entry. An expired row matches no predicate here,
// so a caller can never observe a stale value even before the purge runs.
func (q *Queries) GetCacheEntry(ctx context.Context, key string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getCacheEntry, key)
	var value json.RawMessage
	err := row.Scan(&value)
	return value, err
}

const incrementCacheCounter = `-- name: IncrementCacheCounter :one
INSERT INTO
    cache (key, value, expires_at)
VALUES
    (
        $1,
        '1'::JSONB,
        NOW() + MAKE_INTERVAL(secs => $2::INT)
    )
ON CONFLICT (key) DO UPDATE
SET
    value = CASE
        WHEN cache.expires_at IS NULL
        OR cache.expires_at <= NOW() THEN '1'::JSONB
        ELSE TO_JSONB((cache.value)::TEXT::INT + 1)
    END,
    expires_at = CASE
        WHEN cache.expires_at IS NULL
        OR cache.expires_at <= NOW() THEN NOW() + MAKE_INTERVAL(secs => $2::INT)
        ELSE cache.expires_at
    END,
    created_at = cache.created_at
RETURNING
    (value)::TEXT::INT AS hits,
    expires_at
`

type IncrementCacheCounterParams struct {
	Key           string `json:"key"`
	WindowSeconds int32  `json:"window_seconds"`
}

type IncrementCacheCounterRow struct {
	Hits      int32              `json:"hits"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// IncrementCacheCounter bumps a fixed-window counter and returns its new value
// together with the instant the window closes.
//
// The upsert and the conditional window reset are ONE statement on purpose. A
// read-then-write loses increments under concurrency — two callers both read N
// and both write N+1 — which is precisely the failure a rate limiter must not
// have. Here the ON CONFLICT path takes a row lock, so concurrent callers are
// serialized by Postgres and every hit is counted exactly once.
//
// The first hit, or a hit arriving after the window lapsed, restarts the window
// at 1. A hit inside a live window increments and leaves expires_at alone, so a
// blocked caller cannot extend their own penalty window by retrying.
func (q *Queries) IncrementCacheCounter(ctx context.Context, arg IncrementCacheCounterParams) (IncrementCacheCounterRow, error) {
	row := q.db.QueryRow(ctx, incrementCacheCounter, arg.Key, arg.WindowSeconds)
	var i IncrementCacheCounterRow
	err := row.Scan(&i.Hits, &i.ExpiresAt)
	return i, err
}

const listCacheKeysByPattern = `-- name: ListCacheKeysByPattern :many
SELECT
    key
FROM
    cache
WHERE
    key LIKE $1
    AND (
        expires_at IS NULL
        OR expires_at > NOW()
    )
ORDER BY
    key
`

func (q *Queries) ListCacheKeysByPattern(ctx context.Context, pattern string) ([]string, error) {
	rows, err := q.db.Query(ctx, listCacheKeysByPattern, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredCacheEntries = `-- name: PurgeExpiredCacheEntries :execrows
DELETE FROM cache
WHERE
    expires_at IS NOT NULL
    AND expires_at <= NOW()
`

// PurgeExpiredCacheEntries reaps rows the reads already ignore. Without it the
// table grows forever, since a lapsed rate-limit window is never revisited.
func (q *Queries) PurgeExpiredCacheEntries(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredCacheEntries)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCacheEntry = `-- name: SetCacheEntry :exec
INSERT INTO
    cache (key, value, expires_at)
VALUES
    (
        $1,
        $2,
        CASE
            WHEN $3::INT > 0 THEN NOW() + MAKE_INTERVAL(secs => $3::INT)
            ELSE NULL
        END
    )
ON CONFLICT (key) DO UPDATE
SET
    value = EXCLUDED.value,
    expires_at = EXCLUDED.expires_at,
    created_at = NOW()
`

type SetCacheEntryParams struct {
	Key        string          `json:"key"`
	Value      json.RawMessage `json:"value"`
	TtlSeconds int32           `json:"ttl_seconds"`
}

// SetCacheEntry writes or replaces an entry. A ttl_seconds of 0 stores an entry
// that never expires; created_at is refreshed because a replaced value is a new
// entry, not an update to the old one.
func (q *Queries) SetCacheEntry(ctx context.Context, arg SetCacheEntryParams) error {
	_, err := q.db.Exec(ctx, setCacheEntry, arg.Key, arg.Value, arg.TtlSeconds)
	return err
}
