// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BillingCycle string

const (
	BillingCycleMonthly BillingCycle = "monthly"
	BillingCycleYearly  BillingCycle = "yearly"
)

func (e *BillingCycle) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingCycle(s)
	case string:
		*e = BillingCycle(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingCycle: %T", src)
	}
	return nil
}

type NullBillingCycle struct {
	BillingCycle BillingCycle `json:"billing_cycle"`
	Valid        bool         `json:"valid"` // Valid is true if BillingCycle is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingCycle) Scan(value interface{}) error {
	if value == nil {
		ns.BillingCycle, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingCycle.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingCycle) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingCycle), nil
}

type RoleType string

const (
	RoleTypeAdmin    RoleType = "admin"
	RoleTypeTenant   RoleType = "tenant"
	RoleTypeCustomer RoleType = "customer"
)

func (e *RoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleType(s)
	case string:
		*e = RoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleType: %T", src)
	}
	return nil
}

type NullRoleType struct {
	RoleType RoleType `json:"role_type"`
	Valid    bool     `json:"valid"` // Valid is true if RoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.RoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleType), nil
}

type TenantStatus string

const (
	TenantStatusTrial     TenantStatus = "trial"
	TenantStatusActive    TenantStatus = "active"
	TenantStatusSuspended TenantStatus = "suspended"
	TenantStatusDisabled  TenantStatus = "disabled"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus `json:"tenant_status"`
	Valid        bool         `json:"valid"` // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type AuthUser struct {
	ID            int64              `json:"id"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	Phone         string             `json:"phone"`
	PhoneVerified bool               `json:"phone_verified"`
	Password      string             `json:"password"`
	Role          RoleType           `json:"role"`
	TenantID      *int32             `json:"tenant_id"`
	CustomerID    *int64             `json:"customer_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID          int64              `json:"id"`
	TenantID    int32              `json:"tenant_id"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	AddressBook []byte             `json:"address_book"`
	Settings    []byte             `json:"settings"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SubscriptionPlan struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	Price        pgtype.Numeric     `json:"price"`
	BillingCycle BillingCycle       `json:"billing_cycle"`
	MaxOrders    *int32             `json:"max_orders"`
	Features     []byte             `json:"features"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID                    int32              `json:"id"`
	SubscriptionPlanID    *int32             `json:"subscription_plan_id"`
	FullName              string             `json:"full_name"`
	CompanyName           string             `json:"company_name"`
	Domain                string             `json:"domain"`
	Status                NullTenantStatus   `json:"status"`
	StoreSettings         []byte             `json:"store_settings"`
	PaymentConfig         []byte             `json:"payment_config"`
	AdminSettings         []byte             `json:"admin_settings"`
	SuspendedAt           pgtype.Timestamptz `json:"suspended_at"`
	SubscriptionStartDate pgtype.Timestamptz `json:"subscription_start_date"`
	SubscriptionEndDate   pgtype.Timestamptz `json:"subscription_end_date"`
	TrialStartDate        pgtype.Timestamptz `json:"trial_start_date"`
	TrialEndDate          pgtype.Timestamptz `json:"trial_end_date"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}
