// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tenants.sql

package sqlc

import (
	"context"
)

const getTenantFromHost = `-- name: GetTenantFromHost :one
SELECT
    id
FROM
    tenants
WHERE
    domain = $1::TEXT
`

func (q *Queries) GetTenantFromHost(ctx context.Context, host string) (int32, error) {
	row := q.db.QueryRow(ctx, getTenantFromHost, host)
	var id int32
	err := row.Scan(&id)
	return id, err
}
