// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createAdminUser = `-- name: CreateAdminUser :exec
INSERT INTO
    auth_users (
        email,
        phone,
        password,
        role,
        tenant_id,
        customer_id
    )
VALUES
    (
        LOWER($1),
        $2,
        $3,
        'admin'::role_type, -- Admin role
        NULL, -- No tenant ID
        NULL -- No customer ID
    )
RETURNING
    id
`

type CreateAdminUserParams struct {
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error {
	_, err := q.db.Exec(ctx, createAdminUser, arg.Email, arg.Phone, arg.Password)
	return err
}

const getUser = `-- name: GetUser :one
SELECT
    id, email, email_verified, phone, phone_verified, password, role, created_at, updated_at
FROM
    auth_users
WHERE
    email = LOWER($1)
`

func (q *Queries) GetUser(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDetails = `-- name: GetUserDetails :one
SELECT
    id, email, email_verified, phone, phone_verified, password, role, created_at, updated_at
FROM
    auth_users au
WHERE
    au.email = $1
`

func (q *Queries) GetUserDetails(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserDetails, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVerification = `-- name: UpdateVerification :execrows
UPDATE auth_users
SET
    email_verified = $1,
    phone_verified = $2
WHERE
    id = $3
`

type UpdateVerificationParams struct {
	Emailverified bool  `json:"emailverified"`
	Phoneverified bool  `json:"phoneverified"`
	Userid        int64 `json:"userid"`
}

func (q *Queries) UpdateVerification(ctx context.Context, arg UpdateVerificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVerification, arg.Emailverified, arg.Phoneverified, arg.Userid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
