// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO
    auth_users (
        email,
        phone,
        password,
        role,
        tenant_id,
        customer_id
    )
VALUES
    (
        LOWER($1),
        $2,
        $3,
        'admin'::role_type, -- Admin role
        NULL, -- No tenant ID
        NULL -- No customer ID
    )
RETURNING
    id
`

type CreateAdminUserParams struct {
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.Email, arg.Phone, arg.Password)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCustomerUser = `-- name: CreateCustomerUser :one
WITH
    new_customer AS (
        INSERT INTO
            customers (tenant_id, first_name, last_name)
        VALUES
            (
                CURRENT_SETTING('app.current_tenant')::INT, -- Current tenant ID
                $4,
                $5
            )
        RETURNING
            id AS customer_id
    )
INSERT INTO
    auth_users (
        email,
        phone,
        password,
        role,
        tenant_id,
        customer_id
    )
SELECT
    LOWER($1),
    $2,
    $3,
    'customer'::role_type,
    CURRENT_SETTING('app.current_tenant')::INT, -- Tenant ID
    customer_id
FROM
    new_customer
RETURNING
    id
`

type CreateCustomerUserParams struct {
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Password  string `json:"password"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
}

func (q *Queries) CreateCustomerUser(ctx context.Context, arg CreateCustomerUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCustomerUser,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Firstname,
		arg.Lastname,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTenantUser = `-- name: CreateTenantUser :one
WITH
    new_tenant AS (
        INSERT INTO
            tenants (full_name, company_name, domain)
        VALUES
            ($4, $5, $6)
        RETURNING
            id AS tenant_id
    )
INSERT INTO
    auth_users (
        email,
        phone,
        password,
        role,
        tenant_id,
        customer_id
    )
SELECT
    LOWER($1),
    $2,
    $3,
    'tenant'::role_type,
    tenant_id,
    NULL -- No customer ID for tenant
FROM
    new_tenant
RETURNING
    id
`

type CreateTenantUserParams struct {
	Email       string `json:"email"`
	Phone       string `json:"phone"`
	Password    string `json:"password"`
	Fullname    string `json:"fullname"`
	Companyname string `json:"companyname"`
	Domain      string `json:"domain"`
}

func (q *Queries) CreateTenantUser(ctx context.Context, arg CreateTenantUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTenantUser,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Fullname,
		arg.Companyname,
		arg.Domain,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUser = `-- name: GetUser :one
SELECT
    id, email, email_verified, phone, phone_verified, password, role, tenant_id, customer_id, created_at, updated_at
FROM
    auth_users
WHERE
    email = LOWER($1)
`

func (q *Queries) GetUser(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Password,
		&i.Role,
		&i.TenantID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDetails = `-- name: GetUserDetails :one
SELECT
    -- auth_user columns
    au.id, au.email, au.email_verified, au.phone, au.phone_verified, au.password, au.role, au.tenant_id, au.customer_id, au.created_at, au.updated_at,
    -- tenants cloumns
    t.full_name AS tenant_name,
    t.company_name AS tenant_company_name,
    t.domain AS tenant_domain,
    t.status AS tenant_status,
    t.store_settings AS tenant_store_settings,
    t.payment_config AS tenant_payment_config,
    t.admin_settings AS tenant_admin_settings,
    t.suspended_at AS tenant_suspended_at,
    t.created_at AS tenant_created_at,
    t.updated_at AS tenant_updated_at,
    -- customer columns
    c.first_name AS customer_first_name,
    c.last_name AS customer_last_name,
    c.address_book AS customer_address_book,
    c.settings AS customer_settings,
    c.created_at AS customer_created_at
FROM
    auth_users au
    LEFT JOIN tenants t ON au.tenant_id = t.id
    LEFT JOIN customers c ON au.customer_id = c.id
WHERE
    au.email = $1
    AND (
        (
            au.role = 'admin'
            AND au.tenant_id IS NULL
            AND au.customer_id IS NULL
        )
        OR (
            au.role = 'tenant'
            AND au.tenant_id IS NOT NULL
            AND au.customer_id IS NULL
        )
        OR (
            au.role = 'customer'
            AND au.tenant_id IS NOT NULL
            AND au.customer_id IS NOT NULL
        )
    )
`

type GetUserDetailsRow struct {
	ID                  int64              `json:"id"`
	Email               string             `json:"email"`
	EmailVerified       bool               `json:"email_verified"`
	Phone               string             `json:"phone"`
	PhoneVerified       bool               `json:"phone_verified"`
	Password            string             `json:"password"`
	Role                RoleType           `json:"role"`
	TenantID            *int32             `json:"tenant_id"`
	CustomerID          *int64             `json:"customer_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TenantName          *string            `json:"tenant_name"`
	TenantCompanyName   *string            `json:"tenant_company_name"`
	TenantDomain        *string            `json:"tenant_domain"`
	TenantStatus        NullTenantStatus   `json:"tenant_status"`
	TenantStoreSettings []byte             `json:"tenant_store_settings"`
	TenantPaymentConfig []byte             `json:"tenant_payment_config"`
	TenantAdminSettings []byte             `json:"tenant_admin_settings"`
	TenantSuspendedAt   pgtype.Timestamptz `json:"tenant_suspended_at"`
	TenantCreatedAt     pgtype.Timestamptz `json:"tenant_created_at"`
	TenantUpdatedAt     pgtype.Timestamptz `json:"tenant_updated_at"`
	CustomerFirstName   *string            `json:"customer_first_name"`
	CustomerLastName    *string            `json:"customer_last_name"`
	CustomerAddressBook []byte             `json:"customer_address_book"`
	CustomerSettings    []byte             `json:"customer_settings"`
	CustomerCreatedAt   pgtype.Timestamptz `json:"customer_created_at"`
}

func (q *Queries) GetUserDetails(ctx context.Context, email string) (GetUserDetailsRow, error) {
	row := q.db.QueryRow(ctx, getUserDetails, email)
	var i GetUserDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Password,
		&i.Role,
		&i.TenantID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantName,
		&i.TenantCompanyName,
		&i.TenantDomain,
		&i.TenantStatus,
		&i.TenantStoreSettings,
		&i.TenantPaymentConfig,
		&i.TenantAdminSettings,
		&i.TenantSuspendedAt,
		&i.TenantCreatedAt,
		&i.TenantUpdatedAt,
		&i.CustomerFirstName,
		&i.CustomerLastName,
		&i.CustomerAddressBook,
		&i.CustomerSettings,
		&i.CustomerCreatedAt,
	)
	return i, err
}

const updateVerification = `-- name: UpdateVerification :execrows
UPDATE auth_users
SET
    email_verified = $1,
    phone_verified = $2
WHERE
    id = $3
`

type UpdateVerificationParams struct {
	Emailverified bool  `json:"emailverified"`
	Phoneverified bool  `json:"phoneverified"`
	Userid        int64 `json:"userid"`
}

func (q *Queries) UpdateVerification(ctx context.Context, arg UpdateVerificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVerification, arg.Emailverified, arg.Phoneverified, arg.Userid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
